### ISSUE TITLE
great_migration.rb:58:in `private': nil is not a symbol (TypeError)

### ISSUE THREAD

**Issue by meandkareem** [cannikin/great-migration#2]
when I start process this is error I get

**Comment by cannikin** [comment]
What version of Ruby are you using? The syntax used here is meant to be used in Ruby 2.0 or greater. If you can't upgrade your Ruby then you'll want to update lines 58 and 84 to remove the `private` keyword:

`private def copy_files(page, files)`

becomes

`def copy_files(page, files)`
