### ISSUE TITLE
Option for Public Setting

### ISSUE THREAD

**Issue by dagostinelli** [cannikin/great-migration#6]
It would be helpful to have a command line option to control the public setting.  The `copy_file` function is setting public=true all the time.  That resulted in an Access Denied error that was tough to track down.  By default, buckets are not public, so this wasn't an obvious issue.  (1+ hours of messing around with IAM settings before I found it)

`:public       => false)`

**Comment by cannikin** [comment]
I haven't used this library in years, so it's effectively unmaintained at this point, sorry about that! I'll leave a note at the top of the README. But if you wanted to add this functionality via a PR I'd be happy to merge it for future generations. :)

**Comment by dagostinelli** [comment]
I think the note in the README is a good move.  I since moved on and used rclone to copy local and not place files in S3. So I likely won't do the work.

**Comment by cannikin** [comment]
Updated the README, thanks!
